# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(408, 300)
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(10, 10, 391, 241))
        self.listView.setObjectName("listView")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 260, 211, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.newEntryButton = QtWidgets.QPushButton(Dialog)
        self.newEntryButton.setGeometry(QtCore.QRect(220, 257, 31, 21))
        self.newEntryButton.setObjectName("newEntryButton")
        self.removeEntryButton = QtWidgets.QPushButton(Dialog)
        self.removeEntryButton.setGeometry(QtCore.QRect(245, 257, 31, 21))
        self.removeEntryButton.setObjectName("removeEntryButton")
        self.closeButton = QtWidgets.QPushButton(Dialog)
        self.closeButton.setGeometry(QtCore.QRect(290, 257, 113, 32))
        self.closeButton.setObjectName("closeButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление"))
        self.newEntryButton.setText(_translate("Dialog", "+"))
        self.removeEntryButton.setText(_translate("Dialog", "-"))
        self.closeButton.setText(_translate("Dialog", "Вернуться"))
